name: Build and Release Extension

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create ZIP File
        run: |
          zip -r Zero-New-Tab-Page.zip . -x "*.git*" -x ".github/*" -x "screenshots/*" -x "README.md"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build CRX File
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          cat << 'EOF' > key.pem
          ${{ secrets.PRIVATE_KEY }}
          EOF
          
          unzip -q Zero-New-Tab-Page.zip -d temp_build
          npx crx3 --key key.pem --crx Zero-New-Tab-Page.crx temp_build
          rm -rf key.pem temp_build

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Zero-New-Tab-Page.zip
            Zero-New-Tab-Page.crx
